services:
  - type: web
    name: chit-chat
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chitchat-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: chit-chat
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: chitchat-db
    plan: free
    ipAllowList: []